# Generated by Django 5.0.3 on 2024-03-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0003_alter_vacancy_options_alter_sector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
