# Generated by Django 5.0.3 on 2024-03-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0006_application_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(default='d@dd.com', max_length=254),
            preserve_default=False,
        ),
    ]
