# Generated by Django 5.0.3 on 2024-03-30 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0007_alter_application_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='hours_from',
            field=models.TimeField(default='7:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='hours_to',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
