# Generated by Django 5.0.3 on 2024-03-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0008_vacancy_hours_from_vacancy_hours_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='gender',
            field=models.CharField(choices=[('Male/Female', 'Male/Female'), ('Male', 'Male'), ('Female', 'Female')], default='Male/Female', max_length=20),
        ),
    ]
