# Generated by Django 5.0.3 on 2024-03-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0010_alter_vacancy_hours_from_alter_vacancy_hours_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
