# Generated by Django 5.0.3 on 2024-07-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0015_alter_application_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(blank=True, to='agencyapp.vacancy'),
        ),
    ]
