# Generated by Django 5.0.3 on 2024-07-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0016_user_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite',
        ),
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='users', to='agencyapp.vacancy'),
        ),
    ]
