# Generated by Django 5.0.3 on 2024-09-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0025_application_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Auth_user', '1150'), ('staff', '2250'), ('admin', '1001')], default='Auth_user', max_length=20),
        ),
    ]
