# Generated by Django 5.0.3 on 2024-09-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0026_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1150', 'Auth_user'), ('2250', 'staff'), ('1001', 'admin')], default='1150', max_length=20),
        ),
    ]
