# Generated by Django 5.0.3 on 2024-09-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0027_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('auth_user', 'auth_user'), ('staff', 'staff'), ('admin', 'admin')], default='auth_user', max_length=20),
        ),
    ]
