# Generated by Django 5.0.3 on 2024-09-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0030_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
